improved ArgTrace's creation speed
ftsrg/theta pull request #137
Opened 2021-08-30 16:56 UTC by asztrikx

Instead of inserting at first index reverse at the end.

Also did some benchmark on "selected models", there's no consistent, noticeable difference.

2021-08-30 19:59 UTC, hajduakos commented
Looks good. Can you please bump the patch version number?

2021-08-30 19:59 UTC, hajduakos requested changes
Can you please bump the patch version number?

2021-08-30 20:32 UTC, asztrikx commented
done, thanks for warning

2021-08-31 09:32 UTC, hajduakos approved these changes

2021-08-31 09:32 UTC, merged