XCFA-refactor 2023 [draft]
ftsrg/theta pull request #198
Opened 2023-07-13 10:19 UTC by leventeBajczi

This PR merges the `xcfa-refactor` branch.

TODO description

2023-09-10 13:20 UTC, leventeBajczi commented
@csanadtelbisz: Sonar fails, because some tests ultimately fail.
Relevant log:
``` 
Caused by:
2023-09-10T13:13:40.7201330Z         java.lang.UnsupportedOperationException: Solver Z3 not supported
2023-09-10T13:13:40.7201918Z             at hu.bme.mit.theta.solver.SolverManager.resolveSolverFactory(SolverManager.java:40)
2023-09-10T13:13:40.7202556Z             at hu.bme.mit.theta.xcfa.passes.LoopUnrollPass.<clinit>(LoopUnrollPass.kt:46)
2023-09-10T13:13:40.7202939Z             ... 5 more
```
Can you take a look if this has something to do with the moved registerSolverFactories method in XcfaCli? I think I saw some modifications there in your pr (#202). Let me know if I'm mistaken.

2023-09-10 21:35 UTC, csanadtelbisz commented
@leventeBajczi The solver issue arose due to the fact that `LoopUnrollPass` invokes a solver (unprecedented in xcfa passes before). Tests did not register solvers. I added a dependency on Z3 and hardcoded the usage of Z3 in `LoopUnrollPass`.
Also fixed bugs reported by sonarcloud.

2023-09-12 13:12 UTC, szdan97 commented
A projection should be given in XcfaAnalysis.getXcfaAbstractor in order to avoid performance degradation compared to the original xcfa analysis, as the lack of non-trivial projection leads to a lot of unnecessary covering checks

2023-09-12 20:08 UTC, csanadtelbisz commented
The WebDebuggerLogger is always enabled and it is responsible for a considerable portion of runtime. See the following lines: https://github.com/ftsrg/theta/blob/0c8bc7c48fc89bce04ac1bdd331ad8af7dfc55ff/subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/cegar/CegarChecker.java#L98-L101
As it serves only debugging purposes, it should be disabled by default.
@AdamZsofi git blame shows that you are the author of this change.

The following profiler output confirms the problem. The WebDebuggerLogger takes ~1/3 (more than 10 seconds in this case) of all CPU time.
![image](https://github.com/ftsrg/theta/assets/56129746/8c594586-6dbe-4ecb-834d-1973cf0bc82c)

2023-09-17 07:41 UTC, csanadtelbisz commented
Wrong result is given for the unreach-call property on the following tasks in the eca-rers2012 category of sv-benchmarks:

Config 1: `--strategy DIRECT --maxenum 1 --loglevel RESULT --refinement SEQ_ITP --lbe LBE_SEQ --search ERR --prunestrategy FULL --predsplit ATOMS --cex-monitor DISABLE --domain EXPL`
Problem17_label11.yml

Config 2: `--strategy DIRECT --maxenum 1 --loglevel RESULT --refinement SEQ_ITP --lbe LBE_SEQ --search ERR --prunestrategy FULL --predsplit ATOMS --cex-monitor DISABLE --domain PRED_CART`
Problem10_label30.yml, Problem11_label40.yml, Problem15_label49.yml

2023-10-05 10:00 UTC, as3810t requested changes
All in all, this is an immense PR. I would like to ask for clarification on the following major things:

- With the (re)introduction of the LLVM frontend, Theta had its first cpp module. What is the relation between the `frontends/llvm` submodule, the `libtheta-llvm.so` library, and the `theta-c-frontend` repository?
  - If I interpret it correctly, `theta-c-frontend` was migrated into  `frontends/llvm`, but without its project history, and `libtheta-llvm.so` is the built version of `frontends/llvm`
  - Can we / should we migrate the history of `theta-c-frontend`?
  - Should we ship with a prebuilt version of `libtheta-llvm.so`?
- The XCFA `ProcedurePassManager` seems to enable no passes for CHC's. Is it intentional, or a regression error?
- Other minor things in comments.

2023-10-05 10:00 UTC, as3810t commented on subprojects/frontends/llvm/build.gradle.kts
> +/*
What is the relation of this module to `libtheta-llvm.so` in the `lib`?

2023-10-05 10:00 UTC, as3810t commented on subprojects/xcfa/litmus-cli/src/main/java/hu/bme/mit/theta/xcfa/litmus/cli/LitmusCli.java
> +//            final List<Integer> processIds = listToRange(processes, -1, -1);
Major block of code commented out

2023-10-05 10:00 UTC, as3810t commented on subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/mcm/analysis/FiniteStateChecker.kt
> +class FiniteStateChecker<S : ExplState, A : StmtAction, T>(
Please add documentation (or links to papers) that describe what this algorithm can be used for.

2023-10-05 10:00 UTC, as3810t commented on subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/mcm/analysis/PartialSolver.kt
> +class PartialSolver<T>(
Please add documentation (or links to papers) that describe what this algorithm can be used for.

2023-10-05 10:00 UTC, as3810t commented on subprojects/xcfa/cat/src/main/java/hu/bme/mit/theta/cat/solver/DatalogSolver.java
> +public class DatalogSolver {
Is this class really needed?

2023-10-05 11:43 UTC, leventeBajczi commented
Thanks for the review! I'll get around to incorporating its findings hopefully this weekend.

2023-10-13 17:48 UTC, csanadtelbisz requested changes
@AdamZsofi  WebDebuggerLogger still has an overhead, see the following lines: https://github.com/ftsrg/theta/blob/fdc40cf95ba46bb8a94a791a785f031db2010a2a/subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/cegar/CegarChecker.java#L94-L95

Time taken by these lines:
![image](https://github.com/ftsrg/theta/assets/56129746/17ee9661-c1d4-49e5-9d3b-82bc8ad93d66)

2023-10-14 20:31 UTC, AdamZsofi commented
> @AdamZsofi WebDebuggerLogger still has an overhead, see the following lines:
> 
> https://github.com/ftsrg/theta/blob/fdc40cf95ba46bb8a94a791a785f031db2010a2a/subprojects/common/analysis/src/main/java/hu/bme/mit/theta/analysis/algorithm/cegar/CegarChecker.java#L94-L95
> 
> Time taken by these lines: ![image](https://user-images.githubusercontent.com/56129746/274990704-17ee9661-c1d4-49e5-9d3b-82bc8ad93d66.png)

Thanks for telling me. Fixed, there should be no overhead now.

2023-10-15 13:46 UTC, csanadtelbisz submitted a review, later dismissed

2024-02-15 17:33 UTC, szdan97 approved these changes

2024-02-15 17:57 UTC, merged