xsts-dev
ftsrg/theta pull request #99
Opened 2020-11-27 11:57 UTC by mondokm

Added XSTS metrics and experimental automatic explicit variable selection for the PROD domain

2020-11-27 12:02 UTC, hajduakos commented on subprojects/xsts-cli/src/main/java/hu/bme/mit/theta/xsts/cli/XstsCli.java
> +	@Parameter(names = "--metrics", description = "Print metrics about the CFA without running the algorithm")
Copy-paste: CFA

2020-11-27 12:02 UTC, hajduakos commented
Can `AutomaticItpRefToProd2ExplPredPrec` be already used? I do not see it as an option in the command line interface.

2020-11-27 12:09 UTC, mondokm commented
Not yet but I can add a command-line option

2020-11-27 12:10 UTC, hajduakos commented
I think it would be a good idea to add as an option. Otherwise, it's just there but it cannot be used. Don't forget to extend the docs as well.

2020-12-01 20:19 UTC, hajduakos commented
@mondokm When you have some time, you can also do #100 as part of this PR

2020-12-17 22:38 UTC, hajduakos requested changes
I've checked the PR and seems good. However, the docs should also be updated:
- [ ] Describe the new `-metrics` argument at https://github.com/ftsrg/theta/blob/master/subprojects/xsts-cli/README.md#arguments
- [ ] Describe the new `PROD_AUTO` option and `--maxpredcount` at https://github.com/ftsrg/theta/blob/master/doc/CEGAR-algorithms.md
- [ ] Describe the PNML fronted at https://github.com/ftsrg/theta/blob/master/subprojects/xsts/README.md. You can also check out the STS related projects on how AIGER is mentioned there, because PNML is similar in this sense. It is probably a good idea to mark this feature as experimental.
- [ ] It might be worth also mentioning in the new possibility for `*.pnml` at the `--model` argument https://github.com/ftsrg/theta/blob/master/subprojects/xsts-cli/README.md#arguments

2021-01-31 15:26 UTC, hajduakos approved these changes

2021-01-31 15:33 UTC, merged